const ADD_TO_CART = 'CARTS/ADD_TO_CARD';
const ADD_LOCAL_DATA_TO_CART = 'CARTS/ADD_LOCAL_DATA_TO_CART';
const CHECKOUT = 'CARTS/CHECKOUT';
const CHANGE_QUANTITY = 'CARTS/CHANGE_QUANTITY';
const REMOVE_PRODUCT_IN_CART = 'CARTS/REMOVE_PRODUCT_IN_CART';
const OPEN_CART = 'CARTS/OPEN_CART';

export {
    ADD_TO_CART,
    ADD_LOCAL_DATA_TO_CART,
    CHECKOUT,
    CHANGE_QUANTITY,
    REMOVE_PRODUCT_IN_CART,
    OPEN_CART,
};
