const ADD_TO_CART = 'CARTS/ADD_TO_CARD';
const CHANGE_QUANTITY = 'CARTS/CHANGE_QUANTITY';
const REMOVE_PRODUCT_IN_CART = 'CARTS/REMOVE_PRODUCT_IN_CART';
const OPEN_CART = 'CARTS/OPEN_CART';

export {
    ADD_TO_CART,
    CHANGE_QUANTITY,
    REMOVE_PRODUCT_IN_CART,
    OPEN_CART,
};
