const GET_ERROR_CODES = 'servers/GET_ERROR_CODES';
const GET_ERROR_CODE = 'servers/GET_ERROR_CODE';
const CREATE_ERROR_CODE = 'servers/CREATE_ERROR_CODE';
const UPDATE_ERROR_CODE = 'servers/UPDATE_ERROR_CODE';
const DELETE_ERROR_CODE = 'servers/DELETE_ERROR_CODE';

const ERROR_CODE_ERROR = 'servers/ERROR_CODE_ERROR'

export {
    GET_ERROR_CODES,
    GET_ERROR_CODE,
    CREATE_ERROR_CODE,
    UPDATE_ERROR_CODE,
    DELETE_ERROR_CODE,
    ERROR_CODE_ERROR,
};
